FROM build:1.0 AS base

FROM oven/bun:alpine AS server

WORKDIR /app

COPY --from=base /build/packages/server/dist ./dist
COPY --from=base /build/packages/server/package.json .

RUN apk update && apk add poppler-utils --no-cache

ENV PORT=8080
ENV ENV="production"
ENV OPEN_AI_API_KEY ${OPEN_AI_API_KEY}
EXPOSE ${PORT}

CMD [ "bun","run","start" ]



