FROM build:latest AS base

FROM oven/bun:alpine AS server-test

WORKDIR /app

COPY --from=base /build/packages/server/package.json .
COPY --from=base /build/packages/server/dist-test/ ./dist

RUN apk update && apk add poppler-utils --no-cache

ENV PORT=3001
ENV ENV="development"
ENV OPEN_AI_API_KEY ${OPEN_AI_API_KEY}
ENV FIRESTORE_EMULATOR_HOST=localhost:8080
ENV FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
ENV FIRESTORE_PROJECT_ID=test

EXPOSE ${PORT}

CMD [ "bun","run","start" ]



