services:
  emulator:
    build:
      context: ./
      dockerfile: Dockerfile.emulator
      args:
        - FIREBASE_VERSION=13.3.0
    environment:
      GCLOUD_PROJECT: "test"
      FORCE_COLOR: "true"
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
