FROM oven/bun:alpine AS base

WORKDIR /build

COPY ./packages ./packages
COPY ./bun.lockb .
COPY ./package.json .

RUN bun install --frozen-lockfile && bun run build:server

WORKDIR /build/packages/server
ENV PORT=8080
ENV ENV="production"
EXPOSE 8080

CMD [ "bun","run","dev" ]
# FROM oven/bun:alpine AS server
#
# WORKDIR /app
#
# COPY --from=base /build/packages/server/dist ./dist
# COPY --from=base /build/packages/server/package.json .
#

