name: Staging deploy
on:
  push:
    branches:
      - staging
    paths:
      - "packages/**"
jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "staging"
      base_ref: ${{ github.event.commits[0].id }}
      previous_ref: ${{ github.event.commits[-1].id }}
    secrets: inherit
