name: Production deploy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    path:
      - "packages/**"
jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
      base_ref: ${{ github.event.commits[0].id }}
      previous_ref: ${{ github.event.commits[-1].id }}
    secrets: inherit
