name: Production deploy
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  deploy-main:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
    secrets: inherit
