name: Production deploy
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  deploy-main:
    name: Deploy to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call deploy
        uses: ./.github/workflows/deploy.yml
        with:
          environment: "production"
