name: Staging deploy
on:
  push:
    branches:
      - staging
jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call deploy
        uses: ./.github/workflows/deploy/
        with:
          environment: "staging"
        secrets: inherit
