name: Staging deploy
on:
  push:
    branches:
      - staging
jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy
        uses: ./.github/workflows/deploy.yml
        with:
          environment: "staging"
