name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Which environment will this be deployed in"
        required: true

env:
  VITE_FIREBASE_API_KEY: ${{secrets.VITE_FIREBASE_API_KEY}}
  VITE_FIREBASE_AUTH_DOMAIN: ${{secrets.VITE_FIREBASE_AUTH_DOMAIN}}
  VITE_FIREBASE_PROJECT_ID: ${{secrets.VITE_FIREBASE_PROJECT_ID}}
  VITE_FIREBASE_STORAGE_BUCKET: ${{secrets.VITE_FIREBASE_STORAGE_BUCKET}}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.VITE_FIREBASE_MESSAGING_SENDER_ID}}
  VITE_FIREBASE_APP_ID: ${{secrets.VITE_FIREBASE_APP_ID}}
  REGISTRY_NAME: ${{vars.REGISTRY_NAME}}
  GCLOUD_PROJECT: ${{vars.GCLOUD_PROJECT}}
  GCLOUD_REGION: ${{vars.GCLOUD_REGION}}
  DB_ID: ${{vars.DB_ID}}
  ENV: ${{inputs.environment}}
  REPORTER_BUCKET: ${{vars.REPORTER_BUCKET}}
  SERVER_SERVICE_ACCOUNT: ${{vars.SERVER_SERVICE_ACCOUNT}}
  REPORTER_SERVICE_ACCOUNT: ${{vars.REPORTER_SERVICE_ACCOUNT}}
  FRONTEND_SERVICE_ACCOUNT: ${{vars.FRONTEND_SERVICE_ACCOUNT}}
  #LAMBDA_SERVICE_ACCOUNT: ${{vars.LAMBDA_SERVICE_ACCOUNT}}

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    strategy:
      matrix:
        package: ["server", "frontend", "test-reporter"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Build
        if: ${{ success() }}
        run: |
          ./scripts/build.sh ${{matrix.package}}
      - name: Auth docker
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin "$REGISTRY_NAME"
      - name: Publish
        if: ${{ success() }}
        run: |
          ./scripts/publish.sh ${{matrix.package}}
      - name: Deploy
        if: ${{ success() }}
        run: |
          ./scripts/deploy.sh ${{matrix.package}}
