name: tests-staging

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - staging
    paths:
      - "packages/**"
  workflow_dispatch:
jobs:
  test-staging:
    uses: ./github/workflows/tests.yml
    with:
      environment: staging
