name: tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  run-tests:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run install
      - run: bun run build:all
      - run: ./scripts/run-docker-tests.sh
      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./html
