name: tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  run-tests:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun dependencies
        uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - name: Build code
        run: bun run build:all
      - name: Run tests
        run: ./scripts/run-docker-tests.sh

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Upload reports to gcs
        env:
          GCP_PROJECT: ${{vars.GCP_PROJECT}}
          REPORTER_BUCKET: ${{vars.REPORTER_BUCKET}}
        run: |
          ./scripts/upload-reports.sh

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./html
